-- Create table for Application Form Submissions
CREATE TABLE public.applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    intent TEXT NOT NULL,
    message TEXT NOT NULL
);

-- Create table for Live Chat Messages
CREATE TABLE public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    username TEXT NOT NULL,
    message TEXT NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

-- Create policies allowing public inserts and reads
CREATE POLICY "Allow public application inserts" 
ON public.applications FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public chat read" 
ON public.chat_messages FOR SELECT USING (true);

CREATE POLICY "Allow public chat write" 
ON public.chat_messages FOR INSERT WITH CHECK (true);

-- Enable Realtime on chat messages table
ALTER PUBLICATION supabase_realtime ADD TABLE public.chat_messages;
